from .concept_recognizer import ConceptRecognizer
from .sdg_target_recognizer import SDGTargetRecognizer
#===============================================================================
# from .sdg_indicator_recognizer import SDGIndicatorRecognizer
#===============================================================================

SDG_COUNT = 17
CARDINAL_NUMBERS = [u"first",u"second",u"third",u"fourth",u"fifth",u"sixth",u"seventh",u"eighth",u"ninth",u"tenth",u"eleventh",u"twelfth",u"thirteenth",u"fourteenth",u"fifteenth",u"sixteenth",u"seventeenth"]
ORDINAL_NUMBERS = [u"1st",u"2nd",u"3rd",u"4th",u"5th",u"6th",u"7th",u"8th",u"9th",u"10th",u"11th",u"12th",u"13th",u"14th",u"15th",u"16th",u"17th"]

class SDGRecognizer(ConceptRecognizer):
	doc_list = [
		[
			('1', u"NO POVERTY: While global poverty rates have been cut by more than half since 2000, one in ten people in developing regions are still living with their families on less than the international poverty line of US$1.90 a day, and there are millions more who make little more than this daily amount. Significant progress has been made in many countries within Eastern and Southeastern Asia, but up to 42% of the population in Sub-Saharan Africa continues to live below the poverty line. Poverty is more than the lack of income and resources to ensure a sustainable livelihood. Its manifestations include hunger and malnutrition, limited access to education and other basic services, social discrimination and exclusion as well as the lack of participation in decision-making. Economic growth must be inclusive to provide sustainable jobs and promote equality. Social protection systems need to be implemented to help alleviate the suffering of disaster-prone countries and provide support in the face of great economic risks. These systems will help strengthen responses by afflicted populations to unexpected economic losses during disasters and will eventually help to end extreme poverty in the most impoverished areas."),
			('2', u"ZERO HUNGER: It is time to rethink how we grow, share and consume our food. If done right, agriculture, forestry and fisheries can provide nutritious food for all and generate decent incomes, while supporting people-centered rural development and protecting the environment. Right now, our soils, freshwater, oceans, forests and biodiversity are being rapidly degraded. Climate change is putting even more pressure on the resources we depend on, increasing risks associated with disasters, such as droughts and floods. Many rural women and men can no longer make ends meet on their land, forcing them to migrate to cities in search of opportunities. Poor food security is also causing millions of children to be stunted, or too short for the ages, due to severe malnutrition. A profound change of the global food and agriculture system is needed if we are to nourish the 815 million people who are hungry today and the additional 2 billion people expected to be undernourished by 2050. Investments in agriculture are crucial to increasing the capacity for agricultural productivity and sustainable food production systems are necessary to help alleviate the perils of hunger."),
			('3', u"GOOD HEALTH AND WELL-BEING: Ensuring healthy lives and promoting the well-being at all ages is essential to sustainable development. Significant strides have been made in increasing life expectancy and reducing some of the common killers associated with child and maternal mortality, but working towards achieving the target of less than 70 maternal deaths per 100,000 live births by 2030 would require improvements in skilled delivery care. Achieving the target of reducing premature deaths due to incommunicable diseases by 1/3 by the year 2030 would also require more efficient technologies for clean fuel use during cooking and education on the risks of tobacco. Many more efforts are needed to fully eradicate a wide range of diseases and address many different persistent and emerging health issues. By focusing on providing more efficient funding of health systems, improved sanitation and hygiene, increased access to physicians and more tips on ways to reduce ambient pollution, significant progress can be made in helping to save the lives of millions."),
			('4', u"QUALITY EDUCATION: Obtaining a quality education is the foundation to creating sustainable development. In addition to improving quality of life, access to inclusive education can help equip locals with the tools required to develop innovative solutions to the world’s greatest problems. Over 265 million children are currently out of school and 22% of them are of primary school age. Additionally, even the children who are attending schools are lacking basic skills in reading and math. In the past decade, major progress has been made towards increasing access to education at all levels and increasing enrollment rates in schools particularly for women and girls. Basic literacy skills have improved tremendously, yet bolder efforts are needed to make even greater strides for achieving universal education goals. For example, the world has achieved equality in primary education between girls and boys, but few countries have achieved that target at all levels of education. The reasons for lack of quality education are due to lack of adequately trained teachers, poor conditions of schools and equity issues related to opportunities provided to rural children. For quality education to be provided to the children of impoverished families, investment is needed in educational scholarships, teacher training workshops, school building and improvement of water and electricity access to schools."),
			('5', u"GENDER EQUALITY: While the world has achieved progress towards gender equality and women’s empowerment under the Millennium Development Goals (including equal access to primary education between girls and boys), women and girls continue to suffer discrimination and violence in every part of the world. Gender equality is not only a fundamental human right, but a necessary foundation for a peaceful, prosperous and sustainable world. Unfortunately, at the current time, 1 in 5 women and girls between the ages of 15-49 have reported experiencing physical or sexual violence by an intimate partner within a 12-month period and 49 countries currently have no laws protecting women from domestic violence. Progress is occurring regarding harmful practices such as child marriage and FGM (Female Genital Mutilation), which has declined by 30% in the past decade, but there is still much work to be done to complete eliminate such practices. Providing women and girls with equal access to education, health care, decent work, and representation in political and economic decision-making processes will fuel sustainable economies and benefit societies and humanity at large. Implementing new legal frameworks regarding female equality in the workplace and the eradication of harmful practices targeted at women is crucial to ending the gender-based discrimination prevalent in many countries around the world."),
			('6', u"CLEAN WATER AND SANITATION: Clean, accessible water for all is an essential part of the world we want to live in and there is sufficient fresh water on the planet to achieve this. However, due to bad economics or poor infrastructure, millions of people including children die every year from diseases associated with inadequate water supply, sanitation and hygiene. Water scarcity, poor water quality and inadequate sanitation negatively impact food security, livelihood choices and educational opportunities for poor families across the world. At the current time, more than 2 billion people are living with the risk of reduced access to freshwater resources and by 2050, at least one in four people is likely to live in a country affected by chronic or recurring shortages of fresh water. Drought in specific afflicts some of the world’s poorest countries, worsening hunger and malnutrition. Fortunately, there has been great progress made in the past decade regarding drinking sources and sanitation, whereby over 90% of the world’s population now has access to improved sources of drinking water. To improve sanitation and access to drinking water, there needs to be increased investment in management of freshwater ecosystems and sanitation facilities on a local level in several developing countries within Sub-Saharan Africa, Central Asia, Southern Asia, Eastern Asia and South-Eastern Asia."),
			('7', u"AFFORDABLE AND CLEAN ENERGY: Energy is central to nearly every major challenge and opportunity the world faces today. Be it for jobs, security, climate change, food production or increasing incomes, access to energy for all is essential. Working towards this goal is especially important as it interlinks with other Sustainable Development Goals. Focusing on universal access to energy, increased energy efficiency and the increased use of renewable energy through new economic and job opportunities is crucial to creating more sustainable and inclusive communities and resilience to environmental issues like climate change. At the current time, there are approximately 3 billion people who lack access to clean-cooking solutions and are exposed to dangerous levels of air pollution. Additionally, slightly less than 1 billion people are functioning without electricity and 50% of them are found in Sub-Saharan Africa alone. Fortunately, progress has been made in the past decade regarding the use of renewable electricity from water, solar and wind power and the ratio of energy used per unit of GDP is also declining. However, the challenge is far from being solved and there needs to be more access to clean fuel and technology and more progress needs to be made regarding integrating renewable energy into end-use applications in buildings, transport and industry. Public and private investments in energy also need to be increased and there needs to be more focus on regulatory frameworks and innovative business models to transform the world’s energy systems."),
			('8', u"DECENT WORK AND ECONOMIC GROWTH: Roughly half the world’s population still lives on the equivalent of about US$2 a day with global unemployment rates of 5.7% and having a job doesn’t guarantee the ability to escape from poverty in many places. This slow and uneven progress requires us to rethink and retool our economic and social policies aimed at eradicating poverty. A continued lack of decent work opportunities, insufficient investments and under-consumption lead to an erosion of the basic social contract underlying democratic societies: that all must share in progress. Even though the average annual growth rate of real GDP per capita worldwide is increasing year on year, there are still many countries in the developing world that are decelerating in their growth rates and moving farther from the 7% growth rate target set for 2030. As labor productivity decreases and unemployment rates rise, standards of living begin to decline due to lower wages. Sustainable economic growth will require societies to create the conditions that allow people to have quality jobs that stimulate the economy while not harming the environment. Job opportunities and decent working conditions are also required for the whole working age population. There needs to be increased access to financial services to manage incomes, accumulate assets and make productive investments. Increased commitments to trade, banking and agriculture infrastructure will also help increase productivity and reduce unemployment levels in the world’s most impoverished regions."),
			('9', u"INDUSTRY, INNOVATION AND INFRASTRUCTURE: Investments in infrastructure – transport, irrigation, energy and information and communication technology – are crucial to achieving sustainable development and empowering communities in many countries. It has long been recognized that growth in productivity and incomes, and improvements in health and education outcomes require investment in infrastructure. Manufacturing is an important driver of economic development and employment. At the current time, however, manufacturing value added per capita is only US$100 in the least developed countries compared to over US$4,500 in Europe and Northern America. Another important factor to consider is the emission of Carbon Dioxide during manufacturing processes. Emissions have decreased over the past decade in many countries but the pace of decline has not been even around the world. Technological progress is the foundation of efforts to achieve environmental objectives, such as increased resource and energy-efficiency. Without technology and innovation, industrialization will not happen, and without industrialization, development will not happen. There needs to be more investments in high-tech products that dominate the manufacturing productions to increase efficiency and a focus on mobile cellular services that increase connections between people."),
			('10', u"REDUCED INEQUALITIES: The international community has made significant strides towards lifting people out of poverty.  The most vulnerable nations – the least developed countries, the landlocked developing countries and the small island developing states – continue to make inroads into poverty reduction.  However, inequality persists and large disparities remain regarding access to health and education services and other assets. There is growing consensus that economic growth is not sufﬁcient to reduce poverty if it is not inclusive and if it does not involve the three dimensions of sustainable development – economic, social and environmental. Fortunately, income inequality has been reduced both between and within countries. At the current time, the per capita income of 60 out of 94 countries with data has risen more rapidly than the national average. There has been some progress regarding creating favorable access conditions for exports from least developing countries as well. To reduce inequality, policies should be universal in principle, paying attention to the needs of disadvantaged and marginalized populations. There needs to be an increase in duty-free treatment and continuation of favoring exports from developing countries, in addition to increasing the share of developing countries’ vote within the IMF. Finally, innovations in technology can help reduce the cost of transferring money for migrant workers."),
			('11', u"SUSTAINABLE CITIES AND COMMUNITIES: Cities are hubs for ideas, commerce, culture, science, productivity, social development and much more. At their best, cities have enabled people to advance socially and economically. With the number of people living within cities projected to rise to 5 billion people by 2030, it’s important that efficient urban planning and management practices are in place to deal with the challenges brought by urbanization. Many challenges exist to maintaining cities in a way that continues to create jobs and prosperity without straining land and resources. Common urban challenges include congestion, lack of funds to provide basic services, a shortage of adequate housing, declining infrastructure and rising air pollution within cities. Rapid urbanization challenges, such as the safe removal and management of solid waste within cities, can be overcome in ways that allow them to continue to thrive and grow, while improving resource use and reducing pollution and poverty. One such example is an increase in municipal waste collection. There needs to be a future in which cities provide opportunities for all, with access to basic services, energy, housing, transportation and more."),
			('12', u"RESPONSIBLE PRODUCTION AND CONSUMPTION: Sustainable consumption and production is about promoting resource and energy efficiency, sustainable infrastructure, and providing access to basic services, green and decent jobs and a better quality of life for all. Its implementation helps to achieve overall development plans, reduce future economic, environmental and social costs, strengthen economic competitiveness and reduce poverty. At the current time, material consumption of natural resources is increasing, particularly within Eastern Asia. Countries are also continuing to address challenges regarding air, water and soil pollution. Since sustainable consumption and production aims at “doing more and better with less,” net welfare gains from economic activities can increase by reducing resource use, degradation and pollution along the whole life cycle, while increasing quality of life. There also needs to be significant focus on operating on supply chain, involving everyone from producer to final consumer. This includes educating consumers on sustainable consumption and lifestyles, providing them with adequate information through standards and labels and engaging in sustainable public procurement, among others."),
			('13', u"CLIMATE ACTION: Climate change is now affecting every country on every continent. It is disrupting national economies and affecting lives, costing people, communities and countries dearly today and even more tomorrow. Weather patterns are changing, sea levels are rising, weather events are becoming more extreme and greenhouse gas emissions are now at their highest levels in history. Without action, the world’s average surface temperature is likely to surpass 3 degrees centigrade this century. The poorest and most vulnerable people are being affected the most. Affordable, scalable solutions are now available to enable countries to leapfrog to cleaner, more resilient economies. The pace of change is quickening as more people are turning to renewable energy and a range of other measures that will reduce emissions and increase adaptation efforts. Climate change, however, is a global challenge that does not respect national borders. It is an issue that requires solutions that need to be coordinated at the international level to help developing countries move toward a low-carbon economy. To strengthen the global response to the threat of climate change, countries adopted the Paris Agreement at the COP21 in Paris, which went into force in November of 2016. In the agreement, all countries agreed to work to limit global temperature rise to well below 2 degrees centigrade. As of April 2018, 175 parties had ratified the Paris Agreement and 10 developing countries had submitted their first iteration of their national adaptation plans for responding to climate change."),
			('14', u"LIFE BELOW WATER: The world’s oceans – their temperature, chemistry, currents and life – drive global systems that make the Earth habitable for humankind. Our rainwater, drinking water, weather, climate, coastlines, much of our food, and even the oxygen in the air we breathe, are all ultimately provided and regulated by the sea. Throughout history, oceans and seas have been vital conduits for trade and transportation. Careful management of this essential global resource is a key feature of a sustainable future. However, at the current time, there is a continuous deterioration of coastal waters owing to pollution and ocean acidification is having an adversarial effect on the functioning of ecosystems and biodiversity. This is also negatively impacting small scale fisheries. Marine protected areas need to be effectively managed and well-resourced and regulations need to be put in place to reduce overfishing, marine pollution and ocean acidification."),
			('15', u"LIFE ON LAND: Forests cover 30.7 per cent of the Earth’s surface and, in addition to providing food security and shelter, they are key to combating climate change, protecting biodiversity and the homes of the indigenous population. By protecting forests, we will also be able to strengthen natural resource management and increase land productivity. At the current time, thirteen million hectares of forests are being lost every year while the persistent degradation of drylands has led to the desertification of 3.6 billion hectares. Even though up to 15% of land is currently under protection, biodiversity is still at risk. Deforestation and desertification – caused by human activities and climate change – pose major challenges to sustainable development and have affected the lives and livelihoods of millions of people in the fight against poverty. Efforts are being made to manage forests and combat desertification. There are two international agreements being implemented currently that promote the use of resources in an equitable way. Financial investments in support of biodiversity are also being provided."),
			('16', u"PEACE, JUSTICE AND STRONG INSTITUTIONS: The threats of international homicide, violence against children, human trafficking and sexual violence are important to address to promote peaceful and inclusive societies for sustainable development. They pave the way for the provision of access to justice for all and for building effective, accountable institutions at all levels. While homicide and trafficking cases have seen significant progress over the past decade, there are still thousands of people at greater risk of intentional murder within Latin America, Sub-Saharan Africa and around Asia. Children’s rights violations through aggression and sexual violence continue to plague many countries around the world, especially as under-reporting and lack of data aggravate the problem. To tackle these challenges and build a more peaceful, inclusive societies, there needs to be more efficient and transparent regulations put in place and comprehensive, realistic government budgets. One of the first steps towards protecting individual rights is the implementation of worldwide birth registration and the creation of more independent national human rights institutions around the world."),
			('17', u"PARTNERSHIPS FOR THE GOALS: A successful sustainable development agenda requires partnerships between governments, the private sector and civil society. These inclusive partnerships built upon principles and values, a shared vision, and shared goals that place people and the planet at the centre, are needed at the global, regional, national and local level. Urgent action is needed to mobilize, redirect and unlock the transformative power of trillions of dollars of private resources to deliver on sustainable development objectives. Long-term investments, including foreign direct investment, are needed in critical sectors, especially in developing countries. These include sustainable energy, infrastructure and transport, as well as information and communications technologies. The public sector will need to set a clear direction. Review and monitoring frameworks, regulations and incentive structures that enable such investments must be retooled to attract investments and reinforce sustainable development. National oversight mechanisms such as supreme audit institutions and oversight functions by legislatures should be strengthened."),
		]
	]
	
	def __init__(self, model_options):
		self.concat_target_definitions = model_options['concat_target_definitions']
		super().__init__(
			group_id=0, 
			model_options=model_options
		)
		
	def get_documents(self, group_id):
		class_documents, class_size = super().get_documents(group_id)
		# Add bias to corpus: Every SDG has its own unique identifier (eg. SDG1 for the first SDG), and this unique identifier is very unlikely to appear in contexts unrelated to Sustainable Development Goals
		bias_documents = [f"SDG{i+1}" for i in range(SDG_COUNT)]
		if self.concat_target_definitions:
			target_definitions = [' '.join(doc[1] for doc in group) for group in SDGTargetRecognizer.doc_list]
			class_documents = [f"SDG{i+1} {doc} {target_definitions[i]}" for i,doc in enumerate(class_documents)]
		else:
			class_documents = [f"SDG{i+1} {doc}" for i,doc in enumerate(class_documents)]
		# Build the joint documents set and print some statistics
		documents = bias_documents + class_documents
		# build word_vectors also for new ad hoc words
		self.nlp.vocab[u"sdg"].vector = self.nlp.vocab[u"sustainable"].vector + self.nlp.vocab[u"development"].vector + self.nlp.vocab[u"goal"].vector
		for i in range(SDG_COUNT):
			self.nlp.vocab[f"sdg{i+1}"].vector = self.nlp.vocab[u"sdg"].vector + self.nlp.vocab[u"{}".format(i+1)].vector
		self.nlp.vocab[u"sdgs"].vector = self.nlp.vocab[u"sustainable"].vector + self.nlp.vocab[u"development"].vector + self.nlp.vocab[u"goals"].vector
		return documents, class_size
	
	def format_query(self, query):
		def manipulator(query):
			query = query.lower()
			query = query.replace(u"sustainable development goal", u"sdg")
			for i in range(SDG_COUNT):
				query = query.replace(f"sdg {i+1}", f"sdg{i+1}")
				query = query.replace(f"goal {i+1}", f"sdg{i+1}")
				query = query.replace(f"{CARDINAL_NUMBERS[i]} sdg", f"sdg{i+1}")
				query = query.replace(f"{ORDINAL_NUMBERS[i]} sdg", f"sdg{i+1}")
			return query
		return super().format_query(query, manipulator)
